### ISSUE TITLE
FreeBSD build fail

### ISSUE THREAD

**Issue by valenpo** [xerial/snappy-java#193]
looks like  io.github.soc.directories doesn't support FreeBSD
```
[debug] Load.apply: config.delegates took 0.758622ms
[error] java.lang.ExceptionInInitializerError
[error] 	at coursier.CoursierPaths.cacheDirectory(CoursierPaths.java:61)
[error] 	at coursier.CachePath.defaultCacheDirectory(CachePath.java:88)
[error] 	at coursier.Cache$.default$lzycompute(Cache.scala:1103)
[error] 	at coursier.Cache$.default(Cache.scala:1103)
[error] 	at coursier.CoursierPlugin$.$anonfun$buildSettings$11(CoursierPlugin.scala:295)
[error] 	at sbt.internal.util.Init$Value.$anonfun$apply$3(Settings.scala:804)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:197)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:214)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:159)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:82)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:93)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:89)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: io.github.soc.directories.UnsupportedOperatingSystemException: Base directories are not supported on FreeBSD
[error] 	at io.github.soc.directories.ProjectDirectories.<clinit>(ProjectDirectories.java:113)
[error] 	at coursier.CoursierPaths.cacheDirectory(CoursierPaths.java:61)
[error] 	at coursier.CachePath.defaultCacheDirectory(CachePath.java:88)
[error] 	at coursier.Cache$.default$lzycompute(Cache.scala:1103)
[error] 	at coursier.Cache$.default(Cache.scala:1103)
[error] 	at coursier.CoursierPlugin$.$anonfun$buildSettings$11(CoursierPlugin.scala:295)
[error] 	at sbt.internal.util.Init$Value.$anonfun$apply$3(Settings.scala:804)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:197)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:214)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:159)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:82)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:93)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:89)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.ExceptionInInitializerError
[error] Use 'last' for the full log.
```

**Comment by xerial** [comment]
Then removing this lime might solve this issue:
https://github.com/xerial/snappy-java/blob/ba3810299c6053d2c05f48824be563cb46b88180/project/plugins.sbt#L7

**Comment by valenpo** [comment]
@xerial thanks! it work now
