### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by darianhickman** [xerial/snappy-java#219]
This message appears while using avro-tools-1.7.4.jar to write an avrofile to local disk. 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.xerial.snappy.SnappyLoader (file:/usr/local/bin/avro-tools-1.7.4.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.xerial.snappy.SnappyLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:317)
	at org.xerial.snappy.SnappyLoader.load(SnappyLoader.java:219)
	at org.xerial.snappy.Snappy.<clinit>(Snappy.java:44)
	at org.apache.avro.file.SnappyCodec.decompress(SnappyCodec.java:58)
	at org.apache.avro.file.DataFileStream$DataBlock.decompressUsing(DataFileStream.java:343)
	at org.apache.avro.file.DataFileStream.hasNext(DataFileStream.java:199)
	at org.apache.avro.tool.DataFileReadTool.run(DataFileReadTool.java:64)
	at org.apache.avro.tool.Main.run(Main.java:80)
	at org.apache.avro.tool.Main.main(Main.java:69)
Caused by: java.lang.UnsatisfiedLinkError: no snappyjava in java.library.path: [/Users/darianhickman/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2654)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:876)
	at java.base/java.lang.System.loadLibrary(System.java:1875)
	at org.xerial.snappy.SnappyNativeLoader.loadLibrary(SnappyNativeLoader.java:52)
	... 13 more
Exception in thread "main" org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] null
	at org.xerial.snappy.SnappyLoader.load(SnappyLoader.java:229)
	at org.xerial.snappy.Snappy.<clinit>(Snappy.java:44)
	at org.apache.avro.file.SnappyCodec.decompress(SnappyCodec.java:58)
	at org.apache.avro.file.DataFileStream$DataBlock.decompressUsing(DataFileStream.java:343)
	at org.apache.avro.file.DataFileStream.hasNext(DataFileStream.java:199)
	at org.apache.avro.tool.DataFileReadTool.run(DataFileReadTool.java:64)
	at org.apache.avro.tool.Main.run(Main.java:80)
	at org.apache.avro.tool.Main.main(Main.java:69)

**Comment by bokken** [comment]
What version of snappy-java is being used? The SnappyLoader class has not
used reflections for quite some time.
