### ISSUE TITLE
How can I decompress .iwa files format? 

### ISSUE THREAD

**Issue by egorbarkovsky** [xerial/snappy-java#267]
Hey, I'm trying to work with iWork 13' Format, and for my aim I have to decompress .iwa files using java. But when I tried to do this using you library, got this: 
`Exception in thread "main" java.io.IOException: FAILED_TO_UNCOMPRESS(5)
	at org.xerial.snappy.SnappyNative.throw_error(SnappyNative.java:112)
	at org.xerial.snappy.SnappyNative.rawUncompress(Native Method)
	at org.xerial.snappy.Snappy.rawUncompress(Snappy.java:478)
	at org.xerial.snappy.Snappy.uncompress(Snappy.java:517)
	at org.xerial.snappy.Snappy.uncompress(Snappy.java:492)
	at Client.main(Client.java:25)
`

How can I prove that?

**Comment by egorbarkovsky** [comment]
@xerial

**Comment by bokken** [comment]
As I read [this](https://github.com/obriensp/iWorkFileFormat/blob/master/Docs/index.md#snappy-compression) description of iwa format, it is loosely the snappy framing format, but does not include required portions of the format.

If it actually adhered to the spec, you could use https://github.com/xerial/snappy-java/blob/master/src/main/java/org/xerial/snappy/SnappyFramedInputStream.java. Based on that doc, however, it seems that will not work. You could use the SnappyFramedInputStream source as a starting point to process the custom framing format of iwa files.

**Comment by egorbarkovsky** [comment]
Thank you for your answer! However, may be you know how can we add this "required Stream Identifier chunk" to the iwa file format buffer? 

> As I read [this](https://github.com/obriensp/iWorkFileFormat/blob/master/Docs/index.md#snappy-compression) description of iwa format, it is loosely the snappy framing format, but does not include required portions of the format.
> 
> If it actually adhered to the spec, you could use https://github.com/xerial/snappy-java/blob/master/src/main/java/org/xerial/snappy/SnappyFramedInputStream.java. Based on that doc, however, it seems that will not work. You could use the SnappyFramedInputStream source as a starting point to process the custom framing format of iwa files.
