### ISSUE TITLE
Support for mac silicon(M1) native library

### ISSUE THREAD

**Issue by dhrsoni19** [xerial/snappy-java#279]
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Mac and os.arch=aarch64
	at org.xerial.snappy.SnappyLoader.findNativeLibrary(SnappyLoader.java:299) ~[snappy-java-1.1.1.3.jar:na]
	at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:163) ~[snappy-java-1.1.1.3.jar:na]

**Comment by dhrsoni19** [comment]
Nvmd just saw the commit looks like just need to update my jars
