### ISSUE TITLE
Incorrect buffer positions in PureJavaSnappy causes IllegalArgumentException with hadoop-common's SnappyCodec

### ISSUE THREAD

**Issue by viirya** [xerial/snappy-java#292]
I'm debugging SnappyCodec related issues in hadoop-common which begins to use snappy-java since Hadoop 3.3.1. The exception I saw is:

```
java.lang.IllegalArgumentException                                                                                                                                                             
        at java.nio.Buffer.limit(Buffer.java:275)                                                                                                                                              
        at org.xerial.snappy.Snappy.uncompress(Snappy.java:553)                                                                                                                                
        at org.apache.hadoop.io.compress.snappy.SnappyDecompressor.decompressDirectBuf(SnappyDecompressor.java:268)                                                                            
        at org.apache.hadoop.io.compress.snappy.SnappyDecompressor.decompress(SnappyDecompressor.java:217)                                                                                     
```

This is caused by incorrect positions in `PureJavaSnappy`.

**Comment by runzexia** [comment]
hi @viirya @xerial  
thanks for fix this, we seems having the same problem, can you help to release a snapshot version for us to try?(main branch github action failed )
