### ISSUE TITLE
android-arm64: No static field [ARRAY_BYTE_BASE_OFFSET] of type I

### ISSUE THREAD

**Issue by guojun12002** [xerial/snappy-java#339]
I got a runtime errror when used jdk8 in android arm64
Caused by: java.lang.NoSuchFieldError: No static field ARRAY_BYTE_BASE_OFFSET of type I in class Lsun/misc/Unsafe; or its superclasses (declaration of 'sun.misc.Unsafe' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at org.xerial.snappy.pure.PureJavaSnappy.uncompressedLength(PureJavaSnappy.java:235)
        at org.xerial.snappy.Snappy.uncompressedLength(Snappy.java:617)
        at org.xerial.snappy.Snappy.uncompress(Snappy.java:491)

**Comment by xerial** [comment]
android arm64 is not yet supported. By adding some build configurations, it can be supported.  https://github.com/xerial/snappy-java/releases/tag/v1.1.9.0

**Comment by xerial** [comment]
android arm64 is not yet supported. By adding some build configurations, it can be supported.  https://github.com/xerial/snappy-java/releases/tag/v1.1.9.0

**Comment by imsudiproy** [comment]
@xerial I can work on this

**Comment by xerial** [comment]
Created a PR for this #442

**Comment by xerial** [comment]
A snapshot version is available here https://oss.sonatype.org/content/repositories/snapshots/org/xerial/snappy/snappy-java/1.1.9.1-30-fd504023-SNAPSHOT/snappy-java-1.1.9.1-30-fd504023-SNAPSHOT.jar

It will be released as a part of snappy-java-1.1.10
