### ISSUE TITLE
libsnappyjava.so can't load on alpine image

### ISSUE THREAD

**Issue by coderzc** [xerial/snappy-java#579]
Hello, when I try to use snappy-java on alpine image, I get the following error, do we have some ideas?

```
java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.10-82d62aa6-8497-418b-a504-c335a58c9f0e-libsnappyjava.so: Error relocating /lib/ld-linux-x86-64.so.2: unsupported relocation type 37
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.base/java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.base/java.lang.System.load(Unknown Source) ~[?:?]
	at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:182) ~[org.xerial.snappy-snappy-java-1.1.10.5.jar:1.1.10.5]
	at org.xerial.snappy.SnappyLoader.loadSnappyApi(SnappyLoader.java:157) ~[org.xerial.snappy-snappy-java-1.1.10.5.jar:1.1.10.5]
	at org.xerial.snappy.Snappy.init(Snappy.java:70) ~[org.xerial.snappy-snappy-java-1.1.10.5.jar:1.1.10.5]
	at org.xerial.snappy.Snappy.<clinit>(Snappy.java:47) ~[org.xerial.snappy-snappy-java-1.1.10.5.jar:1.1.10.5]
	at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:103) ~[org.xerial.snappy-snappy-java-1.1.10.5.jar:1.1.10.5]
	at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:92) ~[org.xerial.snappy-snappy-java-1.1.10.5.jar:1.1.10.5]
	at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:82) ~[org.xerial.snappy-snappy-java-1.1.10.5.jar:1.1.10.5]
```

**Comment by Hc747** [comment]
What version of Alpine are you using? It's not available (maintained) on versions > `3.18`.
